# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthbridge" do
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_amd64.tar.gz"
      sha256 "bdf5a211a73c90a2e91a4b3ef116def3474a1f4d5f32df7d26e783895d825360"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_arm64.tar.gz"
      sha256 "76d34c6c961df4587f8d6346185397b75b75b29828dc17161f24bf84cadaa28d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_amd64.tar.gz"
      sha256 "8ca11e2384f2ac32b37ac6912d6357dbe4535feacc7593ba50bbbc37f939baf2"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_arm64.tar.gz"
      sha256 "35e9075dd292458e15b132443b79632a38229612378e05e65ebdba7a710f0cf1"
    end
  end

  name "healthbridge"
  desc "Read and write Apple Health data via an end-to-end-encrypted relay and iOS companion app."
  homepage "https://github.com/shuyangli/healthbridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthbridge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthbridge"]
    end
  end

  # No zap stanza required

end
