# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthbridge" do
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_amd64.tar.gz"
      sha256 "555cbc789f7942ead13319a2568dfce4aeac46b4c41f42ba8fd6d6c83b3dcccb"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_arm64.tar.gz"
      sha256 "27108f9609892e4e4faddaf910ca43b572a9f85fa2e000a572b9f409bec97737"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_amd64.tar.gz"
      sha256 "265e86fd85a57685901d510192ab4889a631045db19ef87a6d876b8ef66aa4c3"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_arm64.tar.gz"
      sha256 "1aa819f08aca5989a9970cf8e3b4c13066c04469b59ea757d3f90a730bfdf5ae"
    end
  end

  name "healthbridge"
  desc "Read and write Apple Health data via an end-to-end-encrypted relay and iOS companion app."
  homepage "https://github.com/shuyangli/healthbridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthbridge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthbridge"]
    end
  end

  # No zap stanza required

end
