# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthbridge" do
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_amd64.tar.gz"
      sha256 "69842fdc72983765863ad5912c3026bf535d9333e5e419e56281465a8848226e"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_darwin_arm64.tar.gz"
      sha256 "88667db783443ad57303d14e9385ebe11dfa18708ce17e3faf510dc176e2afc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_amd64.tar.gz"
      sha256 "9c94f08074e36a6ff33b5bf5034343e8d70d2626a5fef1f294ea96db60c180aa"
    end
    on_arm do
      url "https://github.com/shuyangli/healthbridge/releases/download/v#{version}/healthbridge_#{version}_linux_arm64.tar.gz"
      sha256 "4a9575c36a240263f044ab29cea52e931ea1ffce7b24aa500b1d1082f653f0a2"
    end
  end

  name "healthbridge"
  desc "Read and write Apple Health data via an end-to-end-encrypted relay and iOS companion app."
  homepage "https://github.com/shuyangli/healthbridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthbridge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthbridge"]
    end
  end

  # No zap stanza required

end
